ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8686/eureka/
  instance:
    prefer-ip-address: true
spring:
  redis:
    host: 127.0.0.1
