server:
  port: 9001
spring:
  profiles:
    active: dev
  application:
    name: blog-encrypt
zuul:
  host:
    connect-timeout-millis: 60000000
    socket-timeout-millis: 60000000
  routes:
    blog-extension: #博客的拓展服务端
      path: /extension/** #配置请求URL的请求规则
      serviceId: blog-extension #指定Eureka注册中心中的服务id
      strip-prefix: true #所有的/extension的请求都进行转发
      sentiviteHeaders:
      customSensitiveHeaders: true #让zuul网关处理cookie和重定向
    blog-server: #服务端
      path: /server/** #配置请求URL的请求规则
      serviceId: blog-server #指定Eureka注册中心中的服务id
      strip-prefix: true #所有的/server的请求都进行转发
      sentiviteHeaders:
      customSensitiveHeaders: true #让zuul网关处理cookie和重定向
    blog‐crawler: #爬虫服务端
      path: /crawler/** #配置请求URL的请求规则
      serviceId: blog‐crawler #指定Eureka注册中心中的服务id
      strip-prefix: true #所有的/server的请求都进行转发
      sentiviteHeaders:
      customSensitiveHeaders: true #让zuul网关处理cookie和重定向

# Disable Hystrix timeout globally (for all services)
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

#hystrix:
#  threadpool:
#    default:
#      coreSize: 100
#  command:
#    default:
#      fallback:
#        isolation:
#          semaphore:
#            maxConcurrentRequests: 50
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 360000
#  metrics:
#    enabled:
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 600000
  ConnectTimeout: 600000

